name:
  CI
on:
  [push, pull_request]
jobs:
  script-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_image: ["ubuntu:18.04", "ubuntu:20.04", "ubuntu:22.04"]
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Launch docker
        uses: wxleong/tpm2-cmd-ref/.github/actions/runScript@master
        with:
          PROJECT_NAME: ${{ github.event.repository.name }}
          DOCKER_IMAGE: ${{ matrix.docker_image }}