name:
  CI
on:
  [push, pull_request]
jobs:
  script-test:
    runs-on: ubuntu-latest
# Due to resource constrained GitHub-hosted runner
# it is not possible to run multiple containers at once
# with the matrix strategy.
#
# DOCKER_IMAGE: ${{ matrix.docker_image }}
#
#    strategy:
#      matrix:
#        docker_image: ["debian:buster", "debian:bullseye", "ubuntu:18.04", "ubuntu:20.04", "ubuntu:22.04"]
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Launch docker container (debian:buster)
        uses: wxleong/tpm2-cmd-ref/.github/actions/runScript@master
        with:
          PROJECT_NAME: ${{ github.event.repository.name }}
          DOCKER_IMAGE: debian:buster
      - name: Launch docker container (debian:bullseye)
        uses: wxleong/tpm2-cmd-ref/.github/actions/runScript@master
        with:
          PROJECT_NAME: ${{ github.event.repository.name }}
          DOCKER_IMAGE: debian:bullseye
      - name: Launch docker container (ubuntu:18.04)
        uses: wxleong/tpm2-cmd-ref/.github/actions/runScript@master
        with:
          PROJECT_NAME: ${{ github.event.repository.name }}
          DOCKER_IMAGE: ubuntu:18.04
      - name: Launch docker container (ubuntu:20.04)
        uses: wxleong/tpm2-cmd-ref/.github/actions/runScript@master
        with:
          PROJECT_NAME: ${{ github.event.repository.name }}
          DOCKER_IMAGE: ubuntu:20.04
      - name: Launch docker container (ubuntu:22.04)
        uses: wxleong/tpm2-cmd-ref/.github/actions/runScript@master
        with:
          PROJECT_NAME: ${{ github.event.repository.name }}
          DOCKER_IMAGE: ubuntu:22.04